version: '3.0'
services: 
  selenium-hub: 
   image: selenium/hub
   ports:
    - "4444:4444"
  node-chrome: 
   image: selenium/node-chrome-debug
   environment:
    HUB_HOST: selenium-hub
   ports:
    - "0.0.0.0:32758-32768:5900"
