version: '3.0'
networks:
 gridDemoSwarm:
  driver: overlay      
services: 
  selenium-hub: 
   image: selenium/hub
   ports:
    - "4444:4444"
   deploy:
    mode: global
    placement:
     constraints:
      - node.role == manager
   networks:
    - gridDemoSwarm
  node-chrome: 
   image: selenium/node-chrome-debug
   environment:
    HUB_HOST: selenium-hub
    HUB_PORT: 4444
   entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
   ports:
    - "32758-32768:5900"
   deploy:
    mode: replicated
    replicas: 1
    placement:
     constraints:
      - node.role == worker
   networks:
    - gridDemoSwarm
