version: '3.0'
services: 
  selenium-hub: 
   image: selenium/hub
   ports:
    - "4444"
  node-chrome: 
   image: selenium/node-chrome-debug
   environment:
    HUB_HOST: selenium-hub
   ports:
    - "5900"
