version: '3.0'
services: 
  selenium-hub: 
   image: selenium/hub
   ports:
    - "4444:4444"
  node-chrome: 
   image: selenium/node-chrome-debug
   environment:
    HUB_HOST: selenium-hub
   ports:
    - "32758-32768:5900"
  node-firefox: 
   image: selenium/node-firefox-debug
   environment:
    HUB_HOST: selenium-hub
   ports:
    - "32769-32779:5900"
