apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose-sample.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: selenium-hub
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose-sample.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: selenium-hub
    spec:
      containers:
      - image: selenium/hub
        imagePullPolicy: IfNotPresent
        name: selenium-hub
        ports:
        - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose-sample.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
spec:
  ports:
  - name: "4444"  
    port: 4444
    nodePort: 30444
  selector:
    io.kompose.service: selenium-hub
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose-sample.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: node-chrome
  name: node-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-chrome
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose-sample.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: node-chrome
    spec:
      containers:
      - env:
        - name: HUB_HOST
          value: selenium-hub
        image: selenium/node-chrome-debug
        imagePullPolicy: IfNotPresent
        name: node-chrome
        ports:
        - containerPort: 5900
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose-sample.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: node-chrome
  name: node-chrome
spec:
  ports:
  - name: "5900"
    port: 5900
    nodePort: 30555
  selector:
    io.kompose.service: node-chrome
  type: NodePort
