apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-apps
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments","deployments/scale"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
